Changes to dlnd to enable dlnd to work with mediator auxiliary file output for glc forcing
NorESMhub/CDEPS pull request #10
Opened 2024-11-24 14:20 UTC by mvertens

### Description of changes
Changes to dlnd to enable dlnd to work with mediator auxiliary file output for glc forcing

### Specific notes
The current implementation of dlnd only works with mct coupler output. Changes are needed for dlnd to still maintain this functionality but also be able read in data using the `cmeps nuopc.runconfig `setting
`     histaux_l2x1yrg = .false.
`
In order to do this - a new mode has been introduced for dlnd in config_component.xml
```
    <desc lnd="DLND[%SCPL][%GCPL]">Data land model (DLND) </desc>
    <desc option="SCPL">snow coupling mode to drive glc with data from cpl7 run) </desc>
    <desc option="GCPL">snow coupling mode to drive glc with data from cmeps run) </desc> <=== new
```
Similarly in` stream_definition_dlnd.xml` a new stream was introduced for the new mode - 
`  <stream_entry name="glc_forcing">`
and the original stream name 
`<stream_entry name="sno.cplhist"> ` has been changed to `<stream_entry name="glc_forcing_mct">` for clarity.

NOTE: there are no out of the box datasets that will be used for the new mode - so xml changes have to be carried out explicitly.

Testing: verified that running the following case 
./create_newcase --case TG1850_f09_tn14_gl4ais8_coldstart_241120 --compset 1850_SATM_DLND%GCPL_SICE_SOCN_SROF_CISM2%AIS-EVOLVE%GRIS-EVOLVE_SWAV --res a%null_l%0.9x1.25_oi%null_r%null_g%ais8:gris4_w%null_z%null_m%tnx1v4 --run-unsupported

2. You need to do an xml change of the following variables (I'll list what I used for  data from @mpetrini-norce)
./xmlchange DLND_CPLHIST_DIR=/cluster/projects/nn11022k/mpet/dataset/cplhist/l0.9x1.25/test_1deg_CAM_CLM_CICE_BLOM_GRISAIS_6
./xmlchange DLND_CPLHIST_CASE=test_1deg_CAM_CLM_CICE_BLOM_GRISAIS_6
./xmlchange DLND_CPLHIST_YR_ALIGN=1
./xmlchange DLND_CPLHIST_YR_START=2
./xmlchange DLND_CPLHIST_YR_END=3

Contributors other than yourself, if any: None

CDEPS Issues Fixed: None

Are there dependencies on other component PRs (if so list): No

Are changes expected to change answers: bfb - this is new functionality

Any User Interface Changes: Yes - new xml mode DLND%GCPL

Testing performed (e.g. aux_cdeps, CESM prealpha, etc): See above

Hashes used for testing: noresm2_5_alpha08 along with this change

2024-11-28 20:34 UTC, gold2718 approved these changes
Approving but please deallocate the strrm_flds_xxx arrays after using them.

2024-11-28 20:34 UTC, gold2718 commented on dlnd/lnd_comp_nuopc.F90
> +          allocate(strm_flds_qice(1:glc_nec+1))
Please deallocate these when they are no longer needed (between lines 570 and 571).

2025-04-11 17:00 UTC, gold2718 requested changes
Better but please fix a few minor things.

2025-04-11 17:00 UTC, gold2718 commented on dlnd/lnd_comp_nuopc.F90
> +          if (lfrac(n) == 0.) fldptr2(:,n) = 1.e30_r8
Constants should have the proper type:
```suggestion
          if (lfrac(n) == 0._r8) fldptr2(:,n) = 1.e30_r8
```

2025-04-11 17:00 UTC, gold2718 commented on dlnd/lnd_comp_nuopc.F90
> +          if (lfrac(n) == 0.) fldptr2(:,n) = 1.e30_r8
Constants should have the proper type:
```suggestion
          if (lfrac(n) == 0._r8) fldptr2(:,n) = 1.e30_r8
```

2025-04-11 17:00 UTC, gold2718 commented on dlnd/lnd_comp_nuopc.F90
> +          if (lfrac(n) == 0.) fldptr2(:,n) = 1.e30_r8
Constants should have the proper type:
```suggestion
          if (lfrac(n) == 0._r8) fldptr2(:,n) = 1.e30_r8
```

2025-04-11 17:00 UTC, gold2718 commented on docn/docn_datamode_multilev_cplhist_mod.F90
> +       end if
Can this block be just:
```suggestion
       write(num_str, '(i0)') n
```

2025-04-11 17:00 UTC, gold2718 commented on docn/docn_datamode_multilev_cplhist_mod.F90
> +       1230., 1290., 1350., 1410., 1470., 1530., 1590., 1650., 1710., 1770. /)
These should all have kind:
```suggestion
  real(r8) :: vertical_levels(nlev_export) = (/  &
       30._r8, 90._r8, 150._r8, 210._r8, 270._r8, 330._r8, 390._r8, 450._r8, 510._r8, 570._r8, &
       630._r8, 690._r8, 750._r8, 810._r8, 870._r8, 930._r8, 990._r8, 1050._r8, 1110._r8, 1170._r8, &
       1230._r8, 1290._r8, 1350._r8, 1410._r8, 1470._r8, 1530._r8, 1590._r8, 1650._r8, 1710._r8, 1770._r8 /)
```

2025-04-11 17:00 UTC, gold2718 commented on docn/docn_datamode_multilev_cplhist_mod.F90
> +          if (fldptr2(idim1,idim2) == 0.) then
Constant should have kind:
```suggestion
          if (fldptr2(idim1,idim2) == 0._r8) then
```

2025-04-11 17:00 UTC, gold2718 commented on docn/docn_datamode_multilev_cplhist_mod.F90
> +          if (fldptr2(idim1,idim2) == 0.) then
Constant should have kind:
```suggestion
          if (fldptr2(idim1,idim2) == 0._r8) then
```

2025-04-11 17:06 UTC, mvertens commented on dlnd/lnd_comp_nuopc.F90
> +          if (lfrac(n) == 0.) fldptr2(:,n) = 1.e30_r8
Done

2025-04-11 17:06 UTC, mvertens commented on dlnd/lnd_comp_nuopc.F90
> +          if (lfrac(n) == 0.) fldptr2(:,n) = 1.e30_r8
Done

2025-04-11 17:07 UTC, mvertens commented on dlnd/lnd_comp_nuopc.F90
> +          if (lfrac(n) == 0.) fldptr2(:,n) = 1.e30_r8
Done

2025-04-11 17:08 UTC, mvertens commented on docn/docn_datamode_multilev_cplhist_mod.F90
> +       end if
Good suggestion. Done.

2025-04-11 17:11 UTC, mvertens commented on docn/docn_datamode_multilev_cplhist_mod.F90
> +       1230., 1290., 1350., 1410., 1470., 1530., 1590., 1650., 1710., 1770. /)
Done

2025-04-11 17:12 UTC, mvertens commented on docn/docn_datamode_multilev_cplhist_mod.F90
> +          if (fldptr2(idim1,idim2) == 0.) then
Done

2025-04-11 17:12 UTC, mvertens commented on docn/docn_datamode_multilev_cplhist_mod.F90
> +          if (fldptr2(idim1,idim2) == 0.) then
Done

2025-04-11 17:12 UTC, mvertens commented on docn/docn_datamode_multilev_cplhist_mod.F90
> +       1230., 1290., 1350., 1410., 1470., 1530., 1590., 1650., 1710., 1770. /)
Done

2025-04-11 18:00 UTC, gold2718 approved these changes
All looks good now, thanks!

2025-04-13 19:11 UTC, mvertens commented
@gold2718 - this is now ready for a review again.

2025-04-13 20:54 UTC, gold2718 approved these changes
Thanks for adding tests!

2025-04-14 08:46 UTC, merged

2025-04-14 08:58 UTC, gold2718 commented
Tagged as `cdeps1.0.70_noresm_v1`
@mvdebolskiy

2025-04-14 10:12 UTC, mvdebolskiy commented
@mvertens @gold2718 gnu gives errors (we set warnings to errors with gnu debug) with debug for unused variables in a private module 
```
Error: Unused PRIVATE module variable ‘vertical_levels’ declared at (1) [-Werror=unused-value]
f951: all warnings being treated as errors
make[2]: *** [docn/CMakeFiles/docn.dir/build.make:179: docn/CMakeFiles/docn.dir/docn_datamode_multilev_cplhist_mod.F90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1447: docn/CMakeFiles/docn.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
There are bunch of those.